KS-10-2 check long Name and Password
polyani/KotlinSprint pull request #11
Opened 2024-09-29 06:50 UTC by polyani

Добрый день! Решение задачи 2 из урока 10

2024-09-29 20:18 UTC, ievetrovdev requested changes

2024-09-29 20:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +    if (countUserLong >= 4 && countUserPassword >= 4) {
Значение в этом коде является магическим числом. Как я мог упоминать раньше – не лучшая практика. Предлагаю вынести в переменную.

2024-09-29 20:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task2.kt
> +fun validationLong(): Boolean {
Думаю, стоит задуматься о единственности ответственности метода. Он берет на себе валидацию сразу двух полей, и еще и их ввод. Это скорее логика для метода main. Тут же стоит реализовать валидацию любой переданной строки (ведь у нас правила валидации одинаковые и для логина и пароля), а ввод пароля и логина вынести в main.

2024-10-03 19:23 UTC, polyani commented
Код изменён.

2024-10-03 21:51 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-10-05 09:13 UTC, merged