KS-10-3 generate Password
polyani/KotlinSprint pull request #12
Opened 2024-09-29 18:09 UTC by polyani

решение задачи 3 из урока 10

2024-09-29 20:37 UTC, ievetrovdev requested changes

2024-09-29 20:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    val passwordNumberChars = setOf('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
Попробуй представить последовательность символов в виде диапазона. Подробнее тут https://ru.wikipedia.org/wiki/ASCII

2024-10-05 10:44 UTC, polyani commented
Не совсем понял. Т.е. надо переделать символы в код ASCII (типа пробел = 32) и подставить в переменную эти цифры?

2024-10-09 15:03 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-10-10 18:21 UTC, merged