KS-11-1 create class user
polyani/KotlinSprint pull request #15
Opened 2024-11-14 21:13 UTC by polyani

решение задачи 1 урока 11
создан класс "User" и 2 объекта этого класса

2024-11-15 07:22 UTC, ievetrovdev requested changes
В аннотации к уроку я упоминаю создавать классы в одном файле. Перемести плиз)

2024-11-15 17:13 UTC, polyani commented
Классы в одном файле с чем? С main-ом? Или один файл для всех классов в уроке?

2024-11-16 08:24 UTC, ievetrovdev requested changes
Одни файл на задачу, то есть все классы которые тобой созданы используются в рамках задачи должны быть в одном файле вместе с main
Сейчас почти правильно, только файл с классом (User.kt) нужно удалить

2024-11-16 10:54 UTC, polyani commented
Привет! Один файл удалил, другой переименовал, согласно традиции.

2024-11-16 14:16 UTC, ievetrovdev approved these changes
Отлично, спасибо

2024-11-16 18:32 UTC, merged