KS-5-6-calc-IMT
polyani/KotlinSprint pull request #18
Opened 2024-11-23 13:01 UTC by polyani

решение задачи 6 из урока 5

2024-11-23 19:02 UTC, ievetrovdev requested changes

2024-11-23 19:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_10/lesson_5/lesson5_task6.kt
> +                imt < 18.5 -> {
А для чего ты используешь вложенный when здесь, нам достаточно эти условия прописать внутри первого when

2024-11-23 19:23 UTC, polyani commented
Да, что-то меня занесло )

2024-11-24 13:51 UTC, ievetrovdev approved these changes

2024-11-24 13:51 UTC, ievetrovdev commented on src/main/kotlin/lesson_1_10/lesson_5/lesson5_task6.kt
> +            println("%.2f".format(imt) + " - ИМТ < 18.5: Недостаточная масса тела")
На самом деле подобное форматирование можно делать еще вот-так:
"%.2f - ИМТ < 18.5: Недостаточная масса тела".format(imt)

2024-11-24 18:03 UTC, polyani commented on src/main/kotlin/lesson_1_10/lesson_5/lesson5_task6.kt
> +            println("%.2f".format(imt) + " - ИМТ < 18.5: Недостаточная масса тела")
спасибо!

2024-11-24 18:03 UTC, merged