KS-8-4 поиск и замена ингр-та
polyani/KotlinSprint pull request #4
Opened 2024-08-14 03:44 UTC by polyani

Решение задачи 4 из урока 8
Поиск ингредиента и его замена в массиве.

2024-08-14 14:11 UTC, ievetrovdev requested changes

2024-08-14 14:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_8/lesson8_task4.kt
> +    var exist = listOfIngredients.contains(inChange) // результат Boolean
Отлично! На самом деле этот код уже хорош, но хочу подсветить один неочевидный момент, который в данном простом случае ни на что не влияет, но может пригодиться в более сложных ситуациях. 
 Конструкции `ingredients.contains(ingredientToReplace)` и `ingredients.indexOf(ingredientToReplace)` внутри себя осуществляют проход по всему списку циклом. То есть, ты два раза делаешь перебор всех элементов цикла. Можно оптимизировать, сделав за if-ом `indexOf`, сохранить в переменную и делать сравнение с `-1` (это то, что возвращает `indexOf` если ничего не нашел). А далее использовать тот же индекс для замены ингредиента

2024-08-20 18:09 UTC, polyani commented on src/main/kotlin/lesson_8/lesson8_task4.kt
> +    var exist = listOfIngredients.contains(inChange) // результат Boolean
долго думал, но так и не смог понять, что нужно сделать.

2024-08-31 11:49 UTC, polyani commented
Привет! Внесены изменения в код, во избежание лишних проходов по массиву.

2024-09-01 14:30 UTC, ievetrovdev approved these changes
Отлично!

2024-09-02 16:35 UTC, merged