KS-9-3 расчет кол-ва ингред-ов
polyani/KotlinSprint pull request #8
Opened 2024-08-25 11:25 UTC by polyani

Решение задачи 3 из урока 9

2024-08-25 14:07 UTC, ievetrovdev requested changes
Используй функцию map для этих целей) и в каждую итерацию будем перемножать элемент коллекции

2024-08-25 14:58 UTC, polyani commented
А как тогда приделать единицы измерения к значениям?

2024-08-26 07:17 UTC, ievetrovdev requested changes
Суть данного здания использовать функцию map() для преобразования списка. Так что можешь сначала сделать список ингредиентов (только их количество) и с помощью функции увеличить их размер умножив на количество порций. вывод в данном задании не так важен. так что на твое усмотрение

2024-09-01 14:31 UTC, ievetrovdev approved these changes

2024-09-02 16:36 UTC, merged