KS-9-4 создание и заполнение списка
polyani/KotlinSprint pull request #9
Opened 2024-08-25 16:53 UTC by polyani

Решение задачи 4 из урока 9

2024-08-26 07:19 UTC, ievetrovdev requested changes

2024-08-26 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task4.kt
> +    val resultList = inputString.split(", ")
Отлично, можно еще короче сделать без дополнительного списка)
Все можно поместить в одной строке.

2024-09-05 18:35 UTC, polyani commented
Исправлен код, убран доп.список.

2024-09-06 07:02 UTC, ievetrovdev approved these changes

2024-09-08 13:13 UTC, merged